version: "3.8"

x-spark-worker-template: &spark-worker-template
    build: ./spark_local
    depends_on:
      - spark
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark:7077
    networks:
      - ml-network
    cpu_percent: 20
    mem_reservation: 1gb

services:
  spark:
    image: bitnami/spark:3.2.1
    environment:
      - SPARK_MODE=master
    ports:
      - "8080:8080"
      - "7077:7077"
    networks:
      - ml-network
    cpu_percent: 20
    mem_reservation: 1gb
  spark-worker:
    <<: *spark-worker-template

networks:
  ml-network:
    external: true
